### ISSUE TITLE
not working in redmine 5.1

### ISSUE THREAD

**Issue by ashrafalzyoud** [westaco/westaco_versions#2]
```
ActionView::Template::Error (undefined method `exists?' for File:Class):
    13: <%= javascript_heads %>
    14: <%= heads_for_theme %>
    15: <%= heads_for_auto_complete(@project) %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
    18: <%= yield :header_tags -%>
    19: </head>
  
plugins/westaco_versions/lib/westaco_versions_hook.rb:5:in `view_layouts_base_html_head'
lib/redmine/hook.rb:66:in `block (2 levels) in call_hook'
lib/redmine/hook.rb:66:in `each'
lib/redmine/hook.rb:66:in `block in call_hook'
lib/redmine/hook.rb:63:in `call_hook'
lib/redmine/hook.rb:101:in `call_hook'
app/views/layouts/base.html.erb:16
lib/redmine/sudo_mode.rb:61:in `sudo_mode'
```

**Comment by ctarara** [comment]
Solved, Please review your rating in Redmine Plugins
